// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfjSr7viwH3-GJIfEF-VXODHIsVtcUMdE',
    appId: '1:771262252625:web:bc4aa1275ddd319c4eda70',
    messagingSenderId: '771262252625',
    projectId: 'hrpb-1977e',
    authDomain: 'hrpb-1977e.firebaseapp.com',
    storageBucket: 'hrpb-1977e.appspot.com',
    measurementId: 'G-0BKGLWL9TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeTnMd-4LwXkc-N6I9dYzLyj568j3Nz2c',
    appId: '1:771262252625:android:d7a178e9e392f2f34eda70',
    messagingSenderId: '771262252625',
    projectId: 'hrpb-1977e',
    storageBucket: 'hrpb-1977e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHcqxLq_9sSvdbiePwYAQNUUgIypAGCOY',
    appId: '1:771262252625:ios:8229dbde09514c8f4eda70',
    messagingSenderId: '771262252625',
    projectId: 'hrpb-1977e',
    storageBucket: 'hrpb-1977e.appspot.com',
    iosBundleId: 'com.example.hrp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHcqxLq_9sSvdbiePwYAQNUUgIypAGCOY',
    appId: '1:771262252625:ios:71afbbb9cac53bfc4eda70',
    messagingSenderId: '771262252625',
    projectId: 'hrpb-1977e',
    storageBucket: 'hrpb-1977e.appspot.com',
    iosBundleId: 'com.example.hrp.RunnerTests',
  );
}
